//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VAFS2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VAFS2_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         102
#define IDS_CONNECTFAILED               103
#define IDR_VAFS2                       104
#define IDR_MAINFRAME                   128
#define IDD_DEBUG                       129
#define IDD_VISION                      131
#define IDD_MODEL_EDIT_DLG              134
#define IDB_BITMAP1                     140
#define IDD_PARAMETERSET                141
#define IDD_INPUTRCP                    142
#define IDD_DELETERCP                   143
#define IDB_BITMAP2                     157
#define IDD_LOGIN                       158
#define IDD_paraproduce                 159
#define IDB_BITMAP3                     162
#define IDC_DEBUG                       1001
#define IDC_START                       1002
#define IDC_STOP                        1003
#define IDC_RESET                       1004
#define IDC_Vision                      1005
#define IDC_softkey                     1005
#define IDC_DEBUG2                      1005
#define IDC_CreateModel                 1006
#define IDC_parasetup                   1006
#define IDC_OpenImage                   1007
#define IDC_photoverify                 1007
#define IDC_softkey2                    1007
#define IDC_StartCollection             1008
#define IDC_cyclephoto                  1008
#define IDC_parameterproduce            1008
#define IDC_SearchObject                1009
#define IDC_counterzero                 1009
#define IDC_metalverify                 1009
#define IDC_EditModel                   1010
#define IDC_Vision2                     1010
#define IDC_LoadModel                   1011
#define IDC_cyclephoto2                 1011
#define IDC_metalangleverify            1011
#define IDC_SaveModel                   1012
#define IDC_Vision21                    1012
#define IDC_StopCollection              1013
#define IDC_Vision22                    1013
#define IDC_Rect                        1014
#define IDC_initposition                1014
#define IDC_cyclephoto3                 1014
#define IDC_ClearRect                   1015
#define IDC_PORFILE_RECT                1016
#define IDC_Vision31                    1016
#define IDC_PORFILE_RECT2               1017
#define IDC_Vision32                    1017
#define IDC_PORFILE_RECT3               1018
#define IDC_Vision41                    1018
#define IDC_PORFILE_RECT4               1019
#define IDC_Vision42                    1019
#define IDC_DRAW_RECT                   1028
#define IDC_DRAW_EDGE                   1029
#define IDC_TIMER                       1030
#define IDC_LIST1                       1031
#define IDC_IMAGE_INFO                  1032
#define IDC_MODEL_RECT                  1033
#define IDC_EDIT1                       1035
#define IDC_EDIT2                       1036
#define IDC_minscore21                  1036
#define IDC_modalyorg                   1036
#define IDC_keypastey                   1036
#define IDC_EDIT3                       1037
#define IDC_mousex                      1037
#define IDC_camera2ydiv                 1037
#define IDC_EDIT4                       1038
#define IDC_mousey                      1038
#define IDC_EDIT5                       1039
#define IDC_EDIT6                       1040
#define IDC_EDIT7                       1041
#define IDC_ADD_EDGE                    1042
#define IDC_DEL_EDGE                    1043
#define IDC_EDIT8                       1044
#define DC_SPIN1                        1045
#define IDC_S1                          1046
#define IDC_S2                          1047
#define IDC_S3                          1048
#define IDC_S4                          1049
#define IDC_PICTURE                     1049
#define IDC_S5                          1050
#define IDC_SLIDER_SHUTTER              1050
#define IDC_S6                          1051
#define IDC_SLIDER_BRIGHT               1051
#define IDC_S7                          1052
#define IDC_SLIDER_GAIN                 1052
#define IDC_S8                          1053
#define IDC_EDIT_SHUTTER                1053
#define IDC_EDIT_contrast               1054
#define IDC_EDIT_GAIN                   1055
#define IDC_XSTEPP                      1056
#define IDC_XSTEPM                      1057
#define IDC_YSTEPP                      1058
#define IDC_YSTEPM                      1059
#define IDC_JOGV                        1060
#define IDC_JOGS                        1061
#define IDC_POSITIONX                   1062
#define IDC_POSITIONY1                  1062
#define IDC_POSITIONY                   1063
#define IDC_POSITIONX1                  1063
#define IDC_LISTOUT                     1064
#define IDC_POSITIONTONGUE              1064
#define IDC_peel                        1064
#define IDC_LISTOUT2                    1065
#define IDC_POSITIONROLLER              1065
#define IDC_YSTEPP2                     1065
#define IDC_pickx                       1066
#define IDC_pusherp                     1066
#define IDC_LISTOUT3                    1066
#define IDC_reloadaixlp                 1066
#define IDC_pastestepp                  1067
#define IDC_photox                      1067
#define IDC_pastex                      1068
#define IDC_loadaxilp                   1068
#define IDC_fixturestepp                1069
#define IDC_rollerfinished              1069
#define IDC_linstepp                    1069
#define IDC_picky                       1070
#define IDC_pickx2                      1070
#define IDC_YSTEPM2                     1070
#define IDC_TONGUESTEPP                 1071
#define IDC_photoy                      1071
#define IDC_linestepp                   1071
#define IDC_loutstepp                   1071
#define IDC_TONGUESTEPM                 1072
#define IDC_pastey                      1072
#define IDC_linestepm                   1072
#define IDC_llstepp                     1072
#define IDC_photox2                     1073
#define IDC_pastexBS                    1073
#define IDC_rollerfinished3             1073
#define IDC_POSITIONZ                   1073
#define IDC_POSITIONmainroller          1073
#define IDC_pastex2                     1074
#define IDC_pastestepm                  1074
#define IDC_photoy3                     1074
#define IDC_photoy2                     1074
#define IDC_reloadstepp                 1074
#define IDC_leftstepp                   1074
#define IDC_rollerfinished2             1075
#define IDC_POSITIONTURNPLATE           1075
#define IDC_zpush                       1075
#define IDC_updownout                   1076
#define IDC_pickxd                      1076
#define IDC_vexmainmotorhigh            1076
#define IDC_mainmotorlength             1077
#define IDC_photoxd                     1077
#define IDC_vexmainmotorlow             1078
#define IDC_pastey2                     1078
#define IDC_pastexd                     1078
#define IDC_fixturedelaytime            1079
#define IDC_pickyd                      1079
#define IDC_picktime                    1080
#define IDC_reloadaixlm                 1080
#define IDC_fixtureouttime              1081
#define IDC_TURNPLATEP                  1081
#define IDC_pushertime                  1082
#define IDC_TURNPLATEM                  1082
#define IDC_vexroller                   1083
#define IDC_loadtime                    1083
#define IDC_POSITIONreload              1083
#define IDC_left                        1083
#define IDC_trunplateout                1084
#define IDC_pasteangle                  1084
#define IDC_photoyd                     1084
#define IDC_vexx                        1085
#define IDC_mstart                      1085
#define IDC_mover                       1086
#define IDC_tongueout                   1086
#define IDC_vexy                        1087
#define IDC_loadaxilm                   1087
#define IDC_currentrcp                  1088
#define IDC_fixturem                    1088
#define IDC_POSITIONload                1088
#define IDC_right                       1088
#define IDC_saveas                      1089
#define IDC_pasteyd                     1089
#define IDC_selectrcp                   1090
#define IDC_pickangled                  1090
#define IDC_delrcp                      1091
#define IDC_pasteangled                 1091
#define IDC_rcplist                     1092
#define IDC_vacuump                     1092
#define IDC_loadpp                      1092
#define IDC_problem                     1093
#define IDC_vturnplates                 1093
#define IDC_vextonguein                 1093
#define IDC_pusher1p                    1093
#define IDC_loadmp                      1093
#define IDC_STATIC1                     1094
#define IDC_pasteangles                 1094
#define IDC_STATICcounter               1094
#define IDC_photoxd2                    1094
#define IDC_vextongueout                1094
#define IDC_photoyd2                    1095
#define IDC_unloadtime                  1095
#define IDC_STATICminder                1095
#define IDC_xcale                       1096
#define IDC_pusherp2                    1096
#define IDC_carryp                      1096
#define IDC_pusher2p                    1096
#define IDC_loadp                       1096
#define IDC_yscale                      1097
#define IDC_TONGUEJOGP                  1097
#define IDC_stateinfo                   1098
#define IDC_xcale2                      1098
#define IDC_xdiv                        1098
#define IDC_OK                          1099
#define IDC_fixtureinfo                 1099
#define IDC_photo2angle                 1099
#define IDC_TONGUEJOGM                  1099
#define IDC_yscale2                     1100
#define IDC_ydiv                        1100
#define IDC_tongueoutd                  1100
#define IDC_tongueind                   1101
#define IDC_photodelay                  1101
#define IDC_currentpassword             1102
#define IDC_vturnplates2                1102
#define IDC_vturnplate                  1102
#define IDC_halfload                    1102
#define IDC_newpassword                 1103
#define IDC_pasteangles2                1103
#define IDC_tonguep2                    1103
#define IDC_photo1angle                 1103
#define IDC_loadopen                    1103
#define IDC_passwordupdatatxt           1104
#define IDC_tonguem2                    1104
#define IDC_carrytime                   1104
#define IDC_flow1p                      1104
#define IDC_unload                      1104
#define IDC_passwordupdata              1105
#define IDC_comno                       1105
#define IDC_zpick                       1105
#define IDC_unloadtime2                 1105
#define IDC_softkey3                    1106
#define IDC_vexroller2                  1106
#define IDC_flow2p                      1106
#define IDC_halfunload                  1106
#define IDC_softkey4                    1107
#define IDC_zvex                        1107
#define IDC_repasteangled               1107
#define IDC_PASTECOUNTER                1108
#define IDC_zphoto                      1108
#define IDC_vacuum2p                    1108
#define IDC_unloadopen                  1108
#define IDC_hour                        1109
#define IDC_unloadvacuump               1109
#define IDC_verifypastex                1109
#define IDC_loadvacuum1p                1109
#define IDC_Lblock                      1109
#define IDC_minute                      1110
#define IDC_verifypastey                1110
#define IDC_loadvacuum2p                1110
#define IDC_Lvacuum                     1110
#define IDC_second                      1111
#define IDC_placestepp                  1111
#define IDC_vload                       1111
#define IDC_rightstepp                  1111
#define IDC_dot1                        1112
#define IDC_fixturevacuump              1112
#define IDC_repastex                    1112
#define IDC_ClipRoller                  1112
#define IDC_dot2                        1113
#define IDC_filmwidth                   1113
#define IDC_repastey                    1113
#define IDC_TRAY                        1113
#define IDC_filmlength                  1114
#define IDC_photor                      1114
#define IDC_TRAYVACUUM                  1114
#define IDC_filmgap                     1115
#define IDC_repasteangle                1115
#define IDC_repastexd                   1115
#define IDC_film                        1116
#define IDC_loadpick                    1116
#define IDC_repasteyd                   1116
#define IDC_PARAPRODUCE                 1117
#define IDC_reloadwaiting               1117
#define IDC_loadz                       1117
#define IDC_loadup                      1117
#define IDC_softkey6                    1118
#define IDC_loadwaiting                 1118
#define IDC_unloadpp                    1118
#define IDC_fixturemove                 1119
#define IDC_loadaxilm2                  1119
#define IDC_unloadmp                    1119
#define IDC_XP                          1120
#define IDC_reloadpush                  1120
#define IDC_unloadz                     1120
#define IDC_loaddown                    1120
#define IDC_photo4angle2                1120
#define IDC_photo4angle                 1120
#define IDC_XM                          1121
#define IDC_loadpush                    1121
#define IDC_cover2                      1121
#define IDC_Pright                      1121
#define IDC_YP                          1122
#define IDC_shieldpaste                 1122
#define IDC_peelstepp                   1122
#define IDC_photo3angle                 1122
#define IDC_YM                          1123
#define IDC_withbeep                    1123
#define IDC_unloadstepp                 1123
#define IDC_ANGLEP                      1124
#define IDC_vexfixturex                 1124
#define IDC_pickangled2                 1124
#define IDC_ANGLEM                      1125
#define IDC_vexfixturey                 1125
#define IDC_unloadposition              1125
#define IDC_testone                     1126
#define IDC_unloadp                     1126
#define IDC_films                       1127
#define IDC_unloadm                     1127
#define IDC_filml                       1128
#define IDC_loadpp2                     1128
#define IDC_phototime                   1129
#define IDC_time                        1129
#define IDC_vexlaod                     1129
#define IDC_loadmp2                     1129
#define IDC_STATIC_img                  1130
#define IDC_vexunlaod                   1130
#define IDC_loadin                      1130
#define IDC_SLIDERcontrast              1131
#define IDC_load0                       1131
#define IDC_unloadpp2                   1131
#define IDC_EDIT1contrast               1132
#define IDC_unload0                     1132
#define IDC_unloadmp2                   1132
#define IDC_zoomp                       1133
#define IDC_load1                       1133
#define IDC_zoomm                       1134
#define IDC_pickangle                   1134
#define IDC_zoompup                     1135
#define IDC_metalscale                  1135
#define IDC_zoomdown                    1136
#define IDC_minscore11                  1136
#define IDC_zoomleft                    1137
#define IDC_tonguein                    1137
#define IDC_mousepointx                 1137
#define IDC_zoomright                   1138
#define IDC_mousepointy                 1138
#define IDC_metalscaley                 1138
#define IDC_searchrange                 1139
#define IDC_loadout                     1139
#define IDC_zpicks                      1140
#define IDC_loadpp3                     1140
#define IDC_PORFILE_RECTvision          1141
#define IDC_searchrange2                1141
#define IDC_loadmp3                     1141
#define IDC_reloadpick                  1142
#define IDC_Probotvacuum                1142
#define IDC_fixturex                    1143
#define IDC_unloadpp3                   1143
#define IDC_fixturey                    1144
#define IDC_unloadmp3                   1144
#define IDC_modalxorg                   1145
#define IDC_numberx                     1145
#define IDC_loaddown3                   1145
#define IDC_loadzz                      1145
#define IDC_keypastex                   1146
#define IDC_numbery                     1146
#define IDC_Ptrun                       1146
#define IDC_camera2xdiv                 1147
#define IDC_Pclip                       1147
#define IDC_stepx                       1148
#define IDC_Pleft2                      1148
#define IDC_Pright2                     1148
#define IDC_center                      1149
#define IDC_stepy                       1149
#define IDC_up1                         1150
#define IDC_verifyinfo                  1150
#define IDC_Pdown                       1150
#define IDC_rightup2                    1151
#define IDC_specialy                    1151
#define IDC_Pflow                       1151
#define IDC_right3                      1152
#define IDC_specialx                    1152
#define IDC_Pleftvacuum                 1152
#define IDC_rightdown4                  1153
#define IDC_counterzero1                1153
#define IDC_coverx                      1153
#define IDC_Prightvacuum                1153
#define IDC_down5                       1154
#define IDC_covery                      1154
#define IDC_SPIN1                       1154
#define IDC_light                       1154
#define IDC_Pdownvacuum                 1154
#define IDC_left7                       1155
#define IDC_loadx                       1155
#define IDC_light2                      1155
#define IDC_BELT                        1155
#define IDC_leftdown6                   1156
#define IDC_loady                       1156
#define IDC_leftup8                     1157
#define IDC_unloadx                     1157
#define IDC_unloady                     1158
#define IDC_unload1                     1159
#define IDC_load2                       1160
#define IDC_unload2                     1161
#define IDC_numberx2                    1162
#define IDC_shieldpaste2                1162
#define IDC_traymode                    1162
#define IDC_vacuum                      9112
#define IDC_upfinishedp                 9113
#define IDC_fixturevacuum               9113
#define IDC_downstartp                  9114
#define IDC_covervacuum                 9114

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
