//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VAFS2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VAFS2_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_VAFS2                       104
#define IDR_MAINFRAME                   128
#define IDD_DEBUG                       129
#define IDD_VISION                      131
#define IDD_MODEL_EDIT_DLG              134
#define IDB_BITMAP1                     140
#define IDD_PARAMETERSET                141
#define IDD_INPUTRCP                    142
#define IDD_DELETERCP                   143
#define IDB_BITMAP2                     157
#define IDD_LOGIN                       158
#define IDD_paraproduce                 159
#define IDB_BITMAP3                     162
#define IDD_SmallKey                    176
#define IDD_IOMONITOR                   177
#define IDB_BITMAP4                     182
#define IDB_BITMAP5                     183
#define IDC_DEBUG                       1001
#define IDC_START                       1002
#define IDC_STOP                        1003
#define IDC_RESET                       1004
#define IDC_Vision                      1005
#define IDC_softkey                     1005
#define IDC_DEBUG2                      1005
#define IDC_lastone                     1005
#define IDC_CreateModel                 1006
#define IDC_parasetup                   1006
#define IDC_OpenImage                   1007
#define IDC_photoverify                 1007
#define IDC_softkey2                    1007
#define IDC_StartCollection             1008
#define IDC_cyclephoto                  1008
#define IDC_parameterproduce            1008
#define IDC_SearchObject                1009
#define IDC_counterzero                 1009
#define IDC_metalverify                 1009
#define IDC_EditModel                   1010
#define IDC_Vision2                     1010
#define IDC_LoadModel                   1011
#define IDC_cyclephoto2                 1011
#define IDC_metalangleverify            1011
#define IDC_SaveModel                   1012
#define IDC_Vision21                    1012
#define IDC_StopCollection              1013
#define IDC_Vision22                    1013
#define IDC_Rect                        1014
#define IDC_initposition                1014
#define IDC_Vision3                     1014
#define IDC_ClearRect                   1015
#define IDC_Vision4                     1015
#define IDC_PORFILE_RECT                1016
#define IDC_Vision31                    1016
#define IDC_PORFILE_RECT2               1017
#define IDC_Vision32                    1017
#define IDC_PORFILE_RECT3               1018
#define IDC_Vision41                    1018
#define IDC_PORFILE_RECT4               1019
#define IDC_Vision42                    1019
#define IDC_DRAW_RECT                   1028
#define IDC_DRAW_EDGE                   1029
#define IDC_TIMER                       1030
#define IDC_LIST1                       1031
#define IDC_IMAGE_INFO                  1032
#define IDC_MODEL_RECT                  1033
#define IDC_EDIT1                       1035
#define IDC_EDIT2                       1036
#define IDC_minscore21                  1036
#define IDC_modalyorg                   1036
#define IDC_keypastey                   1036
#define IDC_EDIT3                       1037
#define IDC_mousex                      1037
#define IDC_camera2ydiv                 1037
#define IDC_EDIT4                       1038
#define IDC_mousey                      1038
#define IDC_EDIT5                       1039
#define IDC_EDIT6                       1040
#define IDC_EDIT7                       1041
#define IDC_ADD_EDGE                    1042
#define IDC_DEL_EDGE                    1043
#define IDC_EDIT8                       1044
#define DC_SPIN1                        1045
#define IDC_S1                          1046
#define IDC_S2                          1047
#define IDC_S3                          1048
#define IDC_S4                          1049
#define IDC_PICTURE                     1049
#define IDC_S5                          1050
#define IDC_SLIDER_SHUTTER              1050
#define IDC_S6                          1051
#define IDC_SLIDER_BRIGHT               1051
#define IDC_S7                          1052
#define IDC_SLIDER_GAIN                 1052
#define IDC_S8                          1053
#define IDC_EDIT_SHUTTER                1053
#define IDC_EDIT_contrast               1054
#define IDC_EDIT_GAIN                   1055
#define IDC_XSTEPP                      1056
#define IDC_XSTEPM                      1057
#define IDC_YSTEPP                      1058
#define IDC_YSTEPM                      1059
#define IDC_JOGV                        1060
#define IDC_JOGS                        1061
#define IDC_POSITIONX                   1062
#define IDC_POSITIONY1                  1062
#define IDC_POSITIONY                   1063
#define IDC_POSITIONX1                  1063
#define IDC_LISTOUT                     1064
#define IDC_POSITIONTONGUE              1064
#define IDC_LISTOUT2                    1065
#define IDC_POSITIONROLLER              1065
#define IDC_YSTEPP2                     1065
#define IDC_LINEJOGP                    1065
#define IDC_pickx                       1066
#define IDC_pusherp                     1066
#define IDC_LISTOUT3                    1066
#define IDC_reloadaixlp                 1066
#define IDC_pastestepp                  1067
#define IDC_photox                      1067
#define IDC_pastex                      1068
#define IDC_loadaxilp                   1068
#define IDC_fixturestepp                1069
#define IDC_rollerfinished              1069
#define IDC_repastexm                   1069
#define IDC_picky                       1070
#define IDC_pickx2                      1070
#define IDC_YSTEPM2                     1070
#define IDC_LINEJOGM                    1070
#define IDC_TONGUESTEPP                 1071
#define IDC_photoy                      1071
#define IDC_linestepp                   1071
#define IDC_TONGUESTEPM                 1072
#define IDC_pastey                      1072
#define IDC_linestepm                   1072
#define IDC_photox2                     1073
#define IDC_pastexBS                    1073
#define IDC_rollerfinished3             1073
#define IDC_POSITIONZ                   1073
#define IDC_POSITIONmainroller          1073
#define IDC_repasteym                   1073
#define IDC_pastex2                     1074
#define IDC_pastestepm                  1074
#define IDC_photoy3                     1074
#define IDC_photoy2                     1074
#define IDC_reloadstepp                 1074
#define IDC_rollerfinished2             1075
#define IDC_POSITIONTURNPLATE           1075
#define IDC_zpush                       1075
#define IDC_updownout                   1076
#define IDC_pickxd                      1076
#define IDC_vexmainmotorhigh            1076
#define IDC_mainmotorlength             1077
#define IDC_photoxd                     1077
#define IDC_vexmainmotorlow             1078
#define IDC_pastey2                     1078
#define IDC_pastexd                     1078
#define IDC_fixturedelaytime            1079
#define IDC_pickyd                      1079
#define IDC_picktime                    1080
#define IDC_reloadaixlm                 1080
#define IDC_fixtureouttime              1081
#define IDC_TURNPLATEP                  1081
#define IDC_pushertime                  1082
#define IDC_TURNPLATEM                  1082
#define IDC_vexroller                   1083
#define IDC_loadtime                    1083
#define IDC_POSITIONreload              1083
#define IDC_trunplateout                1084
#define IDC_pasteangle                  1084
#define IDC_photoyd                     1084
#define IDC_vexx                        1085
#define IDC_mstart                      1085
#define IDC_repasteanglem               1085
#define IDC_mover                       1086
#define IDC_tongueout                   1086
#define IDC_vexy                        1087
#define IDC_loadaxilm                   1087
#define IDC_currentrcp                  1088
#define IDC_fixturem                    1088
#define IDC_POSITIONload                1088
#define IDC_saveas                      1089
#define IDC_pasteyd                     1089
#define IDC_selectrcp                   1090
#define IDC_pickangled                  1090
#define IDC_delrcp                      1091
#define IDC_pasteangled                 1091
#define IDC_rcplist                     1092
#define IDC_vacuump                     1092
#define IDC_problem                     1093
#define IDC_vturnplates                 1093
#define IDC_vextonguein                 1093
#define IDC_pusher1p                    1093
#define IDC_STATIC1                     1094
#define IDC_pasteangles                 1094
#define IDC_STATICcounter               1094
#define IDC_photoxd2                    1094
#define IDC_vextongueout                1094
#define IDC_photoyd2                    1095
#define IDC_unloadtime                  1095
#define IDC_STATICminder                1095
#define IDC_xcale                       1096
#define IDC_pusherp2                    1096
#define IDC_carryp                      1096
#define IDC_pusher2p                    1096
#define IDC_STATICcounter2              1096
#define IDC_yscale                      1097
#define IDC_TONGUEJOGP                  1097
#define IDC_STATICcounter3              1097
#define IDC_stateinfo                   1098
#define IDC_xcale2                      1098
#define IDC_xdiv                        1098
#define IDC_OK                          1099
#define IDC_fixtureinfo                 1099
#define IDC_photo2angle                 1099
#define IDC_TONGUEJOGM                  1099
#define IDC_yscale2                     1100
#define IDC_ydiv                        1100
#define IDC_tongueoutd                  1100
#define IDC_tongueind                   1101
#define IDC_photodelay                  1101
#define IDC_currentpassword             1102
#define IDC_vturnplates2                1102
#define IDC_vturnplate                  1102
#define IDC_load1p                      1102
#define IDC_newpassword                 1103
#define IDC_pasteangles2                1103
#define IDC_tonguep2                    1103
#define IDC_photo1angle                 1103
#define IDC_load2p                      1103
#define IDC_passwordupdatatxt           1104
#define IDC_tonguem2                    1104
#define IDC_carrytime                   1104
#define IDC_flow1p                      1104
#define IDC_passwordupdata              1105
#define IDC_comno                       1105
#define IDC_zpick                       1105
#define IDC_softkey3                    1106
#define IDC_vexroller2                  1106
#define IDC_flow2p                      1106
#define IDC_softkey4                    1107
#define IDC_zvex                        1107
#define IDC_repasteangled               1107
#define IDC_PASTECOUNTER                1108
#define IDC_zphoto                      1108
#define IDC_vacuum2p                    1108
#define IDC_hour                        1109
#define IDC_unloadvacuump               1109
#define IDC_verifypastex                1109
#define IDC_loadvacuum1p                1109
#define IDC_minute                      1110
#define IDC_verifypastey                1110
#define IDC_loadvacuum2p                1110
#define IDC_second                      1111
#define IDC_placestepp                  1111
#define IDC_vload                       1111
#define IDC_dot1                        1112
#define IDC_fixturevacuump              1112
#define IDC_repastex                    1112
#define IDC_dot2                        1113
#define IDC_filmwidth                   1113
#define IDC_repastey                    1113
#define IDC_upfinishedp                 1113
#define IDC_filmlength                  1114
#define IDC_photor                      1114
#define IDC_downstartp                  1114
#define IDC_CASTCOUNTER                 1114
#define IDC_filmgap                     1115
#define IDC_repasteangle                1115
#define IDC_repastexd                   1115
#define IDC_TOTALCOUNTER                1115
#define IDC_film                        1116
#define IDC_loadpick                    1116
#define IDC_repasteyd                   1116
#define IDC_PARAPRODUCE                 1117
#define IDC_reloadwaiting               1117
#define IDC_rightpress                  1117
#define IDC_softkey6                    1118
#define IDC_loadwaiting                 1118
#define IDC_pressvacuum                 1118
#define IDC_fixturemove                 1119
#define IDC_rightpress2                 1119
#define IDC_XP                          1120
#define IDC_reloadpush                  1120
#define IDC_XM                          1121
#define IDC_loadpush                    1121
#define IDC_YP                          1122
#define IDC_shieldpaste                 1122
#define IDC_YM                          1123
#define IDC_withbeep                    1123
#define IDC_ANGLEP                      1124
#define IDC_rollon                      1124
#define IDC_ANGLEM                      1125
#define IDC_presson                     1125
#define IDC_XPm                         1126
#define IDC_XMm                         1127
#define IDC_YPm                         1128
#define IDC_phototime                   1129
#define IDC_time                        1129
#define IDC_STATIC_img                  1130
#define IDC_YMm                         1130
#define IDC_SLIDERcontrast              1131
#define IDC_ANGLEPm                     1131
#define IDC_EDIT1contrast               1132
#define IDC_ANGLEMm                     1132
#define IDC_zoomp                       1133
#define IDC_zoomm                       1134
#define IDC_pickangle                   1134
#define IDC_zoompup                     1135
#define IDC_metalscale                  1135
#define IDC_zoomdown                    1136
#define IDC_minscore11                  1136
#define IDC_zoomleft                    1137
#define IDC_tonguein                    1137
#define IDC_mousepointx                 1137
#define IDC_zoomright                   1138
#define IDC_mousepointy                 1138
#define IDC_metalscaley                 1138
#define IDC_searchrange                 1139
#define IDC_zpicks                      1140
#define IDC_PORFILE_RECTvision          1141
#define IDC_searchrange2                1141
#define IDC_reloadpick                  1142
#define IDC_modalxorg                   1145
#define IDC_keypastex                   1146
#define IDC_camera2xdiv                 1147
#define IDC_MSCOMM1                     1148
#define IDC_center                      1149
#define IDC_up1                         1150
#define IDC_verifyinfo                  1150
#define IDC_rightup2                    1151
#define IDC_downfinished                1151
#define IDC_right3                      1152
#define IDC_upstart                     1152
#define IDC_rightdown4                  1153
#define IDC_counterzero1                1153
#define IDC_down5                       1154
#define IDC_Num0                        1154
#define IDC_counterzero2                1154
#define IDC_left7                       1155
#define IDC_Num1                        1155
#define IDC_counterzero3                1155
#define IDC_leftdown6                   1156
#define IDC_Num2                        1156
#define IDC_leftup8                     1157
#define IDC_Num3                        1157
#define IDC_Num4                        1158
#define IDC_Num5                        1159
#define IDC_Num6                        1160
#define IDC_Num7                        1161
#define IDC_Num8                        1162
#define IDC_Num9                        1163
#define IDC_Num10                       1164
#define IDC_Num11                       1165
#define IDC_Maximum                     1166
#define IDC_Minimum                     1167
#define IDC_Prompt                      1168
#define IDC_Input                       1169
#define IDC_Num12                       1170
#define IDC_Num13                       1171
#define IDC_OUT1_2                      1174
#define IDC_slavenum                    1174
#define IDC_OUT1_3                      1175
#define IDC_STATICupstart               1175
#define IDC_OUT33_2                     1176
#define IDC_STATICdownover              1176
#define IDC_OUT33_3                     1177
#define IDC_STATIClift                  1177
#define IDC_STATICright                 1178
#define IDC_PRESSTURN                   1179
#define IDC_ORG1                        1202
#define IDC_ORG2                        1203
#define IDC_ORG3                        1204
#define IDC_ORG4                        1205
#define IDC_ORG5                        1206
#define IDC_ORG6                        1207
#define IDC_ORG7                        1208
#define IDC_ORG8                        1209
#define IDC_IN1                         2001
#define IDC_IN2                         2002
#define IDC_IN3                         2003
#define IDC_IN4                         2004
#define IDC_IN5                         2005
#define IDC_IN6                         2006
#define IDC_IN7                         2007
#define IDC_IN8                         2008
#define IDC_IN9                         2009
#define IDC_IN10                        2010
#define IDC_IN11                        2011
#define IDC_IN12                        2012
#define IDC_IN13                        2013
#define IDC_IN14                        2014
#define IDC_IN15                        2015
#define IDC_IN16                        2016
#define IDC_IN33                        2033
#define IDC_IN34                        2034
#define IDC_IN35                        2035
#define IDC_IN36                        2036
#define IDC_IN37                        2037
#define IDC_IN38                        2038
#define IDC_IN39                        2039
#define IDC_IN40                        2040
#define IDC_IN41                        2041
#define IDC_IN42                        2042
#define IDC_IN43                        2043
#define IDC_IN44                        2044
#define IDC_IN45                        2045
#define IDC_IN46                        2046
#define IDC_IN47                        2047
#define IDC_IN48                        2048
#define IDC_OUT1_1                      2101
#define IDC_OUT2                        2102
#define IDC_OUT3                        2103
#define IDC_OUT4                        2104
#define IDC_OUT5                        2105
#define IDC_OUT6                        2106
#define IDC_OUT7                        2107
#define IDC_OUT8                        2108
#define IDC_OUT9                        2109
#define IDC_OUT10                       2110
#define IDC_OUT11                       2111
#define IDC_OUT12                       2112
#define IDC_OUT33_1                     2133
#define IDC_OUT34                       2134
#define IDC_OUT35                       2135
#define IDC_OUT36                       2136
#define IDC_OUT37                       2137
#define IDC_OUT38                       2138
#define IDC_OUT39                       2139
#define IDC_OUT40                       2140
#define IDC_OUT41                       2141
#define IDC_OUT42                       2142
#define IDC_OUT43                       2143
#define IDC_OUT44                       2144

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1180
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
